import { useCallback, useEffect, useRef, useState } from 'react';
import { ClockCounterClockwise, CloudArrowUp, Eye, FloppyDisk, Plus, Warning } from '@phosphor-icons/react';
import { useAppErrorSafe } from '@/context/ErrorContext';
import { useI18n } from '@/lib/i18n';
import { ApiError } from '@/lib/api';
import { componentTypes, getDraft, getPanelAudience, listRevisions, publishDraft, readRevision, restoreRevision, saveDraft, setPanelAudience, type PanelDocument, type PanelRevision, type PanelRevisionSummary, type TaxonomyPanel } from '@/lib/northAdmin';
import { addComponent, emptyDocument, hasUnsafeContent } from './contentDocument';

function detail(error: unknown) { return error instanceof ApiError ? `${error.message}${error.requestId ? ` (${error.requestId})` : ''}` : error instanceof Error ? error.message : 'Request failed'; }
export function PanelEditor({ organizationId, panelId }: { organizationId: string; panelId: string }) {
  const { t } = useI18n(); const appError = useAppErrorSafe();
  const [revision, setRevision] = useState<PanelRevision | null>(null); const [document, setDocument] = useState<PanelDocument>(emptyDocument); const [history, setHistory] = useState<PanelRevisionSummary[]>([]); const [inspected, setInspected] = useState<PanelRevision | null>(null); const [error, setError] = useState(''); const [conflict, setConflict] = useState(''); const [denied, setDenied] = useState(false); const [audience, setAudience] = useState<TaxonomyPanel['audienceType']>('ALL_MEMBERS');
  const [busy, setBusy] = useState(false); const timer = useRef<number | null>(null); const dirty = useRef(false); const generation = useRef(0); const queue = useRef<Promise<PanelRevision | null>>(Promise.resolve(null)); const latest = useRef({ organizationId, panelId, document, etag: revision?.etag }); latest.current = { organizationId, panelId, document, etag: revision?.etag };
  const fail = useCallback((value: unknown) => { const api = value as ApiError; if (api.status === 401) appError?.classifyAndRaise(api); if ([401, 403, 404].includes(api.status)) setDenied(true); else setError(detail(value)); }, [appError]);
  const load = useCallback(async () => { setDenied(false); try { const currentAudience = await getPanelAudience(organizationId, panelId); try { const draft = await getDraft(organizationId, panelId); const items = await listRevisions(organizationId, panelId); if (latest.current.organizationId !== organizationId || latest.current.panelId !== panelId) return; setRevision(draft); setDocument(draft.document); setHistory(items); setAudience(currentAudience.type); setConflict(''); } catch (value) { if (value instanceof ApiError && value.status === 404) { if (latest.current.organizationId !== organizationId || latest.current.panelId !== panelId) return; setRevision(null); setDocument(emptyDocument()); setAudience(currentAudience.type); setConflict(''); } else fail(value); } } catch (value) { fail(value); } }, [fail, organizationId, panelId]);
  const persist = useCallback(() => { const run = async () => { const snapshot = latest.current; const capturedGeneration = generation.current; if (snapshot.organizationId !== organizationId || snapshot.panelId !== panelId || !dirty.current) return null; if (hasUnsafeContent(snapshot.document)) { setError(t('admin.editorUnsafe')); return null; } try { const next = await saveDraft(snapshot.organizationId, snapshot.panelId, snapshot.document, snapshot.etag); if (latest.current.organizationId !== snapshot.organizationId || latest.current.panelId !== snapshot.panelId) return null; if (generation.current === capturedGeneration) dirty.current = false; latest.current = { ...latest.current, etag: next.etag }; setRevision(next); const items = await listRevisions(snapshot.organizationId, snapshot.panelId); if (latest.current.organizationId !== snapshot.organizationId || latest.current.panelId !== snapshot.panelId) return null; setHistory(items); setConflict(''); return next; } catch (value) { const api = value as ApiError; if (api.status === 409) setConflict(t('admin.editorConflict')); else fail(value); return null; } }; setBusy(true); const task = queue.current.then(run, run); queue.current = task; return task.finally(() => setBusy(false)); }, [fail, organizationId, panelId, t]);
  const flushLatest = useCallback(async () => { if (timer.current) window.clearTimeout(timer.current); const expected = { organizationId, panelId }; while (dirty.current && latest.current.organizationId === expected.organizationId && latest.current.panelId === expected.panelId) await persist(); await queue.current; return latest.current.organizationId === expected.organizationId && latest.current.panelId === expected.panelId && !dirty.current ? latest.current.etag : undefined; }, [organizationId, panelId, persist]);
  useEffect(() => { dirty.current = false; generation.current = 0; void load(); return () => { if (timer.current) window.clearTimeout(timer.current); }; }, [load]);
  const change = (next: PanelDocument) => { generation.current += 1; dirty.current = true; latest.current = { ...latest.current, document: next }; setDocument(next); if (timer.current) window.clearTimeout(timer.current); timer.current = window.setTimeout(() => void persist(), 900); };
  if (denied) return <p className="p-4 text-sm text-text-muted">{t('admin.unavailableBody')}</p>;
  return <section className="space-y-3 rounded-xl border border-border bg-surface p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-medium">{t('admin.editorTitle')}</h2><div className="flex gap-2"><button type="button" disabled={busy} onClick={() => { if (timer.current) window.clearTimeout(timer.current); void persist(); }} className="rounded-md border border-border px-2 py-1 text-xs disabled:opacity-50"><FloppyDisk className="mr-1 inline h-3 w-3" />{t('admin.editorSave')}</button><button type="button" disabled={!revision || busy} onClick={() => { void flushLatest().then(async (etag) => { if (etag) await publishDraft(organizationId, panelId, etag).then(load); }).catch(fail); }} className="rounded-md bg-accent px-2 py-1 text-xs text-white disabled:opacity-50">{t('admin.editorPublish')}</button></div></div><p className="text-xs text-text-muted">{t('admin.editorStructured')}</p>{error && <p role="alert" className="text-sm text-error">{error}</p>}{conflict && <div role="alert" className="rounded bg-amber-500/10 p-2 text-sm"><Warning className="mr-1 inline h-4 w-4" />{conflict}<button type="button" onClick={() => void load()} className="ml-2 underline">{t('admin.editorReload')}</button></div>}
    <div className="flex flex-wrap gap-1">{componentTypes.map((type) => <button key={type} type="button" disabled={['image','video','file'].includes(type)} onClick={() => change(addComponent(document, type))} className="rounded border border-border px-2 py-1 text-xs disabled:cursor-not-allowed disabled:opacity-40"><Plus className="mr-1 inline h-3 w-3" />{type}</button>)}</div>
    <label className="block text-xs">{t('admin.editorAudience')}<select value={audience} disabled={busy} onChange={(event) => { const type = event.target.value as TaxonomyPanel['audienceType']; if (type === 'ALL_MEMBERS') void setPanelAudience(organizationId, panelId, { type }).then(() => setAudience(type)).catch(fail); else setError(t('admin.editorAudienceReadonly')); }} className="mt-1 w-full rounded border border-border bg-background p-2"><option value="ALL_MEMBERS">ALL_MEMBERS</option><option value="ROLES">ROLES</option><option value="GROUPS">GROUPS</option><option value="PERMISSIONS">PERMISSIONS</option><option value="SPECIFIC_USERS">SPECIFIC_USERS</option></select></label>
    <details><summary className="cursor-pointer text-sm"><Eye className="mr-1 inline h-4 w-4" />{t('admin.editorPreview')}</summary><div className="mt-2 space-y-2 rounded border border-border p-3">{document.sections.flatMap((section) => section.components).map((component) => <div key={component.id} className="rounded border border-border p-2 text-sm"><strong>{component.type}</strong>{component.type === 'heading' && <p className="text-lg">{String((component.props.text as Record<string, string> | undefined)?.es ?? '')}</p>}{component.type === 'link' && <span> {String((component.props.label as Record<string, string> | undefined)?.es ?? '')}</span>}{component.type === 'metric' && <span> {String((component.props.value ?? '—'))}</span>}{['image','video','file'].includes(component.type) && <span className="text-text-muted"> {t('admin.editorAssetUnavailable')}</span>}</div>)}</div></details>
    <label className="block text-xs font-medium">{t('admin.editorDocument')}<textarea value={JSON.stringify(document, null, 2)} onChange={(event) => { try { change(JSON.parse(event.target.value) as PanelDocument); setError(''); } catch { setError(t('admin.editorInvalidJson')); } }} className="mt-1 h-72 w-full rounded border border-border bg-background p-2 font-mono text-xs" /></label><div className="flex items-center gap-2 text-xs text-text-muted"><CloudArrowUp className="h-4 w-4" />{t('admin.editorAssets')}</div>
    {inspected && <section className="rounded border border-border p-2 text-xs"><div className="flex justify-between"><strong>{t('admin.editorInspect')} v{inspected.revisionNumber}</strong><button type="button" onClick={() => setInspected(null)} className="underline">{t('admin.editorBackToDraft')}</button></div><pre className="mt-2 max-h-40 overflow-auto whitespace-pre-wrap">{JSON.stringify(inspected.document, null, 2)}</pre></section>}<details><summary className="cursor-pointer text-sm"><ClockCounterClockwise className="mr-1 inline h-4 w-4" />{t('admin.editorHistory')} ({history.length})</summary><div className="mt-2 space-y-1">{history.map((item) => <div key={item.id} className="flex items-center justify-between text-xs"><span>v{item.revisionNumber} · {new Date(item.createdAt).toLocaleString()}</span><button type="button" disabled={!revision || busy} onClick={() => { if (timer.current) window.clearTimeout(timer.current); if (!revision) return; void persist().then((saved) => restoreRevision(organizationId, panelId, item.id, saved?.etag ?? latest.current.etag ?? revision.etag)).then(async (next) => { latest.current = { ...latest.current, document: next.document, etag: next.etag }; setRevision(next); setDocument(next.document); const items = await listRevisions(organizationId, panelId); if (latest.current.organizationId === organizationId && latest.current.panelId === panelId) setHistory(items); }).catch(fail); }} className="underline disabled:opacity-40">{t('admin.editorRestore')}</button><button type="button" onClick={() => void readRevision(organizationId, panelId, item.id).then(setInspected).catch(fail)} className="underline">{t('admin.editorInspect')}</button></div>)}</div></details></section>;
}
